# -*- coding: utf-8 -*-
"""LangChainDemo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P12ywIZr4-BpcLxRFSMVDApERnYvNwAU
"""

!pip install -q langchain langchain-openai langchain-community faiss-cpu tiktoken

!pip uninstall -y langchain langchain-core langchain-community langgraph
!pip install -U langchain langchain-core langchain-community langgraph

from langchain_openai import ChatOpenAI
print("LangChain 正常")

import langchain_core
print(langchain_core.__version__)

import os
import getpass

os.environ["OPENAI_API_KEY"] = getpass.getpass("请输入你的 OpenAI API Key: ")

"""准备简易知识库"""

from langchain_core.documents import Document

docs = [
    Document(page_content="LangChain 是一个用于构建 LLM 应用的框架。"),
    Document(page_content="RAG 是检索增强生成技术，用于增强大模型回答的准确性。"),
    Document(page_content="Agent 可以调用工具来执行任务。")
]

print("文档创建成功")

"""文档切分"""

from langchain_text_splitters import CharacterTextSplitter

text_splitter = CharacterTextSplitter(
    chunk_size=100,
    chunk_overlap=20
)

split_docs = text_splitter.split_documents(docs)

print(f"切分后的文档数量: {len(split_docs)}")

"""向量化 + 建立向量数据库"""

from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS

embeddings = OpenAIEmbeddings()

vectorstore = FAISS.from_documents(split_docs, embeddings)

retriever = vectorstore.as_retriever()

#embeddings 和长期向量库初始化（运行一次）
import time

long_term_store = FAISS.from_documents(
    [Document(page_content="初始化")],
    embeddings
)

"""创建 LLM"""

from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)

def run_llm(prompt_text: str) -> str:
    result = llm.invoke(prompt_text)
    return result.content

"""定义 Tools"""

from langchain_core.tools import tool
!pip install -q duckduckgo-search
!pip install -U ddgs

# 工具 1：知识库检索
@tool
def search_knowledge_base(query: str) -> str:
    """当用户询问 LangChain、RAG 或 Agent 技术细节时使用。"""
    docs = retriever.invoke(query)
    return "\n\n".join([d.page_content for d in docs])

# 工具 2：长期记忆检索
@tool
def search_long_term_memory(query: str) -> str:
    """当用户询问历史总结或之前对话时使用。"""
    docs = long_term_store.similarity_search(query, k=2)
    return "\n\n".join([d.page_content for d in docs])

from langchain_community.tools import DuckDuckGoSearchRun

# 1. 定义联网搜索工具
@tool
def search_web(query: str) -> str:
    """
    当问题涉及通用知识（如名人、时事、体育、非技术类问题）时，必须使用此工具。
    不要用于 LangChain 或 RAG 的技术定义。
    """
    search = DuckDuckGoSearchRun()
    return search.run(query)

# 2. 更新工具列表（保留原有的）
tools = [search_knowledge_base, search_long_term_memory, search_web]

"""定义prompt"""

from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder

agent_prompt = ChatPromptTemplate.from_messages([
    ("system",
     """你是一个智能助手。

当用户询问 LangChain、RAG、Agent 的技术细节时，
优先调用 search_knowledge_base 工具。

当用户询问历史总结时，
调用 search_long_term_memory 工具。

如果无需查询，直接回答。
"""),
    # 不再用 input / chat_history
])

"""绑定工具到 LLM"""

llm_with_tools = llm.bind_tools(tools)

"""Planner 节点"""

# 引入 DuckDuckGo
from langchain_community.tools import DuckDuckGoSearchRun
search_tool = DuckDuckGoSearchRun()

def planner_node(state):
    print("🔥 进入 planner_node (动态规划)")
    goal = state.get("goal")

    # 核心修改：Prompt 不再强制固定步骤，而是让 LLM 选择工具
    prompt = f"""
    你是一个任务规划师。请根据用户目标生成执行步骤列表。

    可用动作(Action)说明：
    1. "search_local": 仅当问题关于 LangChain, RAG, Agent 等内部技术文档时使用。
    2. "search_web": 当问题关于名人(如 Steph Curry)、时事、通用知识时使用。
    3. "reason": 当问题是逻辑推理、数学计算、或普通闲聊时使用（不需要搜索）。
    4. "output": 最后一步必须是 output。

    用户目标："{goal}"

    请只输出一个 JSON 字符串列表，不要其他废话。
    示例 1 (技术问题): ["search_local", "summarize", "output"]
    示例 2 (通用问题): ["search_web", "summarize", "output"]
    示例 3 (简单对话): ["reason", "output"]
    """

    raw = run_llm(prompt)

    import json, re
    try:
        plan = json.loads(raw)
    except:
        # 正则兜底解析
        match = re.search(r"(\[.*\])", raw, re.S)
        plan = json.loads(match.group(1)) if match else ["reason", "output"]

    print(f"✅ 动态生成的计划: {plan}")

    return {
        "plan": plan,
        "current_step": 0,
        "step_outputs": [],
        "finished": False,
        "critic": {}
    }

"""Executor 节点"""

def executor_node(state):
    plan = state.get("plan")
    idx = state.get("current_step", 0)

    if not plan or idx >= len(plan):
        return {"finished": True}

    step = plan[idx]
    print(f"⚙️ Executor 正在执行: {step}")

    output = ""

    # === 动作分支 ===
    if step == "search_local":
        # 查本地向量库
        docs = retriever.invoke(state["goal"])
        output = f"【本地知识库检索结果】：\n" + "\n".join([d.page_content for d in docs])

    elif step == "search_web":
        # 查 DuckDuckGo
        print("   🌐 正在联网搜索...")
        try:
            web_result = search_tool.invoke(state["goal"])
            output = f"【互联网搜索结果】：\n{web_result}"
        except Exception as e:
            output = f"搜索失败: {str(e)}"

    elif step == "reason":
        # 纯思考/闲聊
        output = run_llm(f"请直接回答或思考以下问题，不要搜索：{state['goal']}")

    elif step == "summarize":
        # 总结前面的搜索结果
        context = "\n\n".join(state.get("step_outputs", []))
        output = run_llm(f"基于以下搜索到的资料，回答用户目标：'{state['goal']}'。\n\n资料：\n{context}")

    elif step == "output":
        # 最终输出整理
        prev_output = state["step_outputs"][-1] if state["step_outputs"] else ""
        output = prev_output # 直接透传上一步的总结

    else:
        # 兜底
        output = run_llm(f"执行步骤 {step}，当前上下文：{state['step_outputs']}")

    return {
        "step_outputs": state.get("step_outputs", []) + [output],
        "current_step": idx + 1
    }

"""Critic 节点"""

def critic_node(state):
    import json, re # Ensure json is imported

    prompt = f"""
你是审稿人。

目标：
{state["goal"]}

步骤结果：
{state["step_outputs"]}

判断：
1. 是否完成目标？
2. 是否需要重做某一步？

输出 JSON：
{{
  "accept": true/false,
  "retry_step": 数字或null
}}
"""

    response = run_llm(prompt)

    try:
        verdict = json.loads(response)
    except:
        match = re.search(r"(\{{.*\}})", response, re.S)
        if match:
            verdict = json.loads(match.group(1))
        else:
            verdict = {"accept": False} # Default to fail if parse error

    print("🧐 Critic verdict:", verdict)

    updates = {"critic": verdict}

    # Increment retries if not accepted
    if not verdict.get("accept"):
        updates["retries"] = state.get("retries", 0) + 1

    return updates

"""构建 LangGraph"""

from langgraph.graph import StateGraph, END
from typing import TypedDict, List, Optional, Dict, Any

# 定义 State 类型，使用 TypedDict
class AgentState(TypedDict, total=False):
    goal: str
    plan: Optional[List[str]]
    current_step: int
    step_outputs: List[str]
    finished: bool
    critic: Dict[str, Any]
    retries: int


graph = StateGraph(AgentState)

graph.add_node("planner", planner_node)
graph.add_node("executor", executor_node)
graph.add_node("critic", critic_node)

graph.set_entry_point("planner")

graph.add_edge("planner", "executor")

def executor_decision(state):
    if state.get("finished"):
        return "critic"
    return "executor"


graph.add_conditional_edges("executor", executor_decision)

def critic_decision(state):
    verdict = state.get("critic", {})
    retries = state.get("retries", 0)

    if verdict.get("accept"):
        print("🎉 Critic accepted!")
        return END

    if retries >= 3:
        print("⚠️ 达到最大重试次数，强制结束")
        return END

    print(f"🔄 Critic rejected (Retries: {retries}). Re-planning...")
    return "planner"

graph.add_conditional_edges("critic", critic_decision)

app = graph.compile()

"""测试运行"""

result = app.invoke({
    "goal": "写一篇关于 RAG 的 300 字中文简介"
}, config={"recursion_limit": 50})

print(result["step_outputs"][-1])

result = app.invoke({
    "goal": "介绍一下Steph Curry"
}, config={"recursion_limit": 50})

print(result["step_outputs"][-1])

result = app.invoke({
    "goal": "给我讲个笑话。"
}, config={"recursion_limit": 50})

print(result["step_outputs"][-1])

